// <auto-generated />
using InterviewQuiz.Access.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewQuiz.Access.Infrastructure.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20260929075008_InitialAccess")]
    partial class InitialAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewQuiz.Access.Domain.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IncludeInEmployeeRoleEditor")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "access");

                    b.HasData(
                        new
                        {
                            Code = "users.manage",
                            DisplayName = "Manage users",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "roles.manage",
                            DisplayName = "Manage permission groups",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.resumes",
                            DisplayName = "Restore archived resumes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.attempts",
                            DisplayName = "Restore archived attempts",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.catalog",
                            DisplayName = "Restore archived quiz content",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "openings.read",
                            DisplayName = "View openings",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "openings.write",
                            DisplayName = "Create and edit openings",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "openings.fields.manage",
                            DisplayName = "Manage opening field defaults",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "quizzes.read",
                            DisplayName = "View quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "quizzes.write",
                            DisplayName = "Create and edit quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "templates.read",
                            DisplayName = "View templates",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "templates.write",
                            DisplayName = "Create and edit templates",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "ai.rules.manage",
                            DisplayName = "Manage company AI rule sets",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "ai.draft.use",
                            DisplayName = "Use AI draft",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "assignments.read",
                            DisplayName = "View assignments",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "assignments.write",
                            DisplayName = "Assign quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "sessions.live.run",
                            DisplayName = "Run live sessions",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "attempts.read",
                            DisplayName = "View attempts and results",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "evaluation"
                        },
                        new
                        {
                            Code = "attempts.review",
                            DisplayName = "Review attempts",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "evaluation"
                        },
                        new
                        {
                            Code = "filters.write",
                            DisplayName = "Manage own saved filters",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "search"
                        },
                        new
                        {
                            Code = "filters.share",
                            DisplayName = "Share saved filters",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "search"
                        },
                        new
                        {
                            Code = "candidate.attempt.participate",
                            DisplayName = "Take and submit own attempt",
                            IncludeInEmployeeRoleEditor = false,
                            Module = "candidate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
