// <auto-generated />
using System;
using InterviewQuiz.Access.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewQuiz.Access.Infrastructure.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    partial class AccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewQuiz.Access.Domain.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("identity_users", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.MagicLinkInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_magic_link_invites_assignment_current")
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("magic_link_invites", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IncludeInEmployeeRoleEditor")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "access");

                    b.HasData(
                        new
                        {
                            Code = "users.manage",
                            DisplayName = "Manage users",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "roles.manage",
                            DisplayName = "Manage permission groups",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.resumes",
                            DisplayName = "Restore archived resumes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.attempts",
                            DisplayName = "Restore archived attempts",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "archive.restore.catalog",
                            DisplayName = "Restore archived quiz content",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "access"
                        },
                        new
                        {
                            Code = "openings.read",
                            DisplayName = "View openings",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "openings.write",
                            DisplayName = "Create and edit openings",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "openings.fields.manage",
                            DisplayName = "Manage opening field defaults",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "openings"
                        },
                        new
                        {
                            Code = "quizzes.read",
                            DisplayName = "View quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "quizzes.write",
                            DisplayName = "Create and edit quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "templates.read",
                            DisplayName = "View templates",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "templates.write",
                            DisplayName = "Create and edit templates",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "questions.read",
                            DisplayName = "View question bank",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "questions.write",
                            DisplayName = "Create and edit question bank",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "ai.rules.manage",
                            DisplayName = "Manage company AI rule sets",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "ai.draft.use",
                            DisplayName = "Use AI draft",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "catalog"
                        },
                        new
                        {
                            Code = "assignments.read",
                            DisplayName = "View assignments",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "assignments.write",
                            DisplayName = "Assign quizzes",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "sessions.live.run",
                            DisplayName = "Run live sessions",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "delivery"
                        },
                        new
                        {
                            Code = "attempts.read",
                            DisplayName = "View attempts and results",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "evaluation"
                        },
                        new
                        {
                            Code = "attempts.review",
                            DisplayName = "Review attempts",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "evaluation"
                        },
                        new
                        {
                            Code = "filters.write",
                            DisplayName = "Manage own saved filters",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "search"
                        },
                        new
                        {
                            Code = "filters.share",
                            DisplayName = "Share saved filters",
                            IncludeInEmployeeRoleEditor = true,
                            Module = "search"
                        },
                        new
                        {
                            Code = "candidate.attempt.participate",
                            DisplayName = "Take and submit own attempt",
                            IncludeInEmployeeRoleEditor = false,
                            Module = "candidate"
                        });
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.UserRoleAssignment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claims", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_logins", "access");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_tokens", "access");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.RefreshToken", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.RolePermission", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewQuiz.Access.Domain.AccessRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.UserRoleAssignment", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.AccessRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewQuiz.Access.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InterviewQuiz.Access.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewQuiz.Access.Domain.AccessRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
