// <auto-generated />
using System;
using System.Collections.Generic;
using InterviewQuiz.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewQuiz.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260930090743_Slice4QuestionBank")]
    partial class Slice4QuestionBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.BankQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ExpectedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<string>("ScoringMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("bank_questions", "catalog");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("ExpectedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<Guid>("OpeningId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginTemplateId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SourceTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpeningId");

                    b.HasIndex("OriginTemplateId");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("quizzes", "catalog");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginQuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OriginQuizId")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("templates", "catalog");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("ExpectedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PublishedFromQuizId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("template_versions", "catalog");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.Quiz", b =>
                {
                    b.OwnsMany("InterviewQuiz.Catalog.Domain.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("CreditMode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ScoringMode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("SourceQuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Stem")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizId", "SortOrder");

                            b1.ToTable("questions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.TemplateVersion", b =>
                {
                    b.HasOne("InterviewQuiz.Catalog.Domain.Template", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("InterviewQuiz.Catalog.Domain.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("CreditMode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<string>("ScoringMode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("SourceQuestionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Stem")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<Guid>("TemplateVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("Id");

                            b1.HasIndex("TemplateVersionId", "SortOrder");

                            b1.ToTable("template_version_questions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TemplateVersionId");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
