// <auto-generated />
using System;
using System.Collections.Generic;
using InterviewQuiz.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewQuiz.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("ExpectedExperienceYears")
                        .HasColumnType("integer");

                    b.Property<Guid>("OpeningId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpeningId");

                    b.HasIndex("Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("quizzes", "catalog");
                });

            modelBuilder.Entity("InterviewQuiz.Catalog.Domain.Quiz", b =>
                {
                    b.OwnsMany("InterviewQuiz.Catalog.Domain.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("CreditMode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ScoringMode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<string>("Stem")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizId", "SortOrder");

                            b1.ToTable("questions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
